### ISSUE TITLE
[Android Studio]Gradle: Error: more than one library with package name 'com.connectsdk'

### ISSUE THREAD

**Issue by kushG** [ConnectSDK/Simple-Photo-Share-Android#2]
I keep getting this error whenever I use connectsdk library. So, I tried working on this project without any modification but no luck ! I get the same error. If I try to add android.enforceuniquePackageName=false then I get a dexDebug TOP-LEVEL EXCEPTION error. 
Below are my gradle files. Since, this might be related only to connectsdk I'm posting it here first. I would be happy to post the same in stackoverflow if this isn't the appropriate place for this issue.

<b>Simple-Photo-Share-Android1 build.gradle :</b>

![simple-photo-share-android1](https://cloud.githubusercontent.com/assets/8779995/8728502/6f97e3fe-2bb3-11e5-998c-1a99fe09c7a3.PNG)

<b>connectSDKAndroid build.gradle :</b>

![connectsdkandroid](https://cloud.githubusercontent.com/assets/8779995/8728517/8d3d377e-2bb3-11e5-9d3e-52933d05492a.PNG)

<b>simple-photo-share-android build.gradle :</b>

![simplephotoshareandroid](https://cloud.githubusercontent.com/assets/8779995/8728531/a0e51e68-2bb3-11e5-964b-81aef03a491b.PNG)

<b>settings.gradle :</b>
include ':connectSDKAndroid'
include ':simplePhotoShareAndroid'

**Comment by frolov-alexey** [comment]
Hi @kushG I've added a build.gradle for this project here https://github.com/ConnectSDK/Simple-Photo-Share-Android/pull/3 You can use it. For more advanced sampler application  please use this project https://github.com/ConnectSDK/Connect-SDK-Android-API-Sampler

**Comment by frolov-alexey** [comment]
Also there is an error in your Connect-SDK-Android build.gradle - you include Connect-SDK-Android into Connect-SDK-Android. It must not have this line `compile 'com.connectsdk:connect-sdk-android:1.4.4'.`

**Comment by kushG** [comment]
Thank you for adding gradle support. Although, I could not fix my issue but I can now run this project after cloning it into a new location.
